arch:
- aarch64
- amd64
- armhf
- armv7
- i386
backup_exclude:
- '*/logs'
codenotary: codenotary@frenck.dev
description: Manage Nginx proxy hosts with a simple, powerful interface
hassio_api: true
image: ghcr.io/hassio-addons/nginxproxymanager/{arch}
init: false
map:
- ssl:rw
- backup:rw
name: Nginx Proxy Manager
ports:
  443/tcp: 443
  80/tcp: 80
  81/tcp: 81
ports_description:
  443/tcp: HTTPS/SSL Entrance port
  80/tcp: HTTP Entrance port
  81/tcp: Proxy management web interface
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reset_database: bool?
services:
- mysql:need
slug: nginxproxymanager
url: https://github.com/hassio-addons/addon-nginx-proxy-manager
version: 0.12.3
webui: http://[HOST]:[PORT:81]
