arch:
- aarch64
- amd64
- armv7
codenotary: codenotary@frenck.dev
description: Open source password management solution
image: ghcr.io/hassio-addons/bitwarden/{arch}
init: false
map:
- ssl
name: Vaultwarden (Bitwarden)
options:
  certfile: fullchain.pem
  keyfile: privkey.pem
  ssl: true
ports:
  7277/tcp: 7277
ports_description:
  7277/tcp: Vaultwarden Web interface
schema:
  certfile: str
  keyfile: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  request_size_limit: int?
  ssl: bool
slug: bitwarden
url: https://github.com/hassio-addons/addon-bitwarden
version: 0.19.0
webui: '[PROTO:ssl]://[HOST]:[PORT:7277]'
