advanced: true
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
codenotary: codenotary@frenck.dev
description: Explore your SQLite database
image: ghcr.io/hassio-addons/sqlite-web/{arch}
ingress: true
init: false
map:
- config:rw
- share:rw
name: SQLite Web
panel_icon: mdi:database
schema:
  database: str?
slug: sqlite-web
url: https://github.com/hassio-addons/addon-sqlite-web/tree/main/README.md
version: 3.7.0
